name: Build ZMK Corne nice!nano

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - board: nice_nano
            shield: corne_left
          - board: nice_nano
            shield: corne_right

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler \
            python3-pip python3-setuptools python3-wheel xz-utils file \
            wget

          pip3 install --user west
          pip3 install --user pyelftools


          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.5/zephyr-sdk-0.16.5_linux-x86_64.tar.xz
          tar xf zephyr-sdk-0.16.5_linux-x86_64.tar.xz

      - name: Setup Zephyr SDK
        run: |
          export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
          export ZEPHYR_SDK_INSTALL_DIR=$PWD/zephyr-sdk-0.16.5
          echo "ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV
          echo "ZEPHYR_SDK_INSTALL_DIR=$PWD/zephyr-sdk-0.16.5" >> $GITHUB_ENV
          cd zephyr-sdk-0.16.5
          ./setup.sh -t arm-zephyr-eabi -h
          cd ..

      - name: Clone ZMK
        run: |
          git clone https://github.com/zmkfirmware/zmk.git

      - name: Init west
        run: |
          cd zmk
          west init -l app
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          cd zmk
          west build -s app -b ${{ matrix.board }} --pristine always -- \
            -DSHIELD=${{ matrix.shield }} \
            -DZMK_CONFIG=$PWD/../config

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.shield }}-${{ matrix.board }}
          path: zmk/build/zephyr/
